lib/manga2gether_web/router.ex
defmodule Manga2getherWeb.Router do
  use Manga2getherWeb, :router

  import Manga2getherWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Manga2getherWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Manga2getherWeb do
    pipe_through [:browser, :require_authenticated_user, :maybe_redirect_room]

    live "/", DashboardLive.Index, :index
    live "/room/new", DashboardLive.Index, :new
    live "/room/:id/edit", DashboardLive.Index, :edit
  end

  scope "/", Manga2getherWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/room/:room_code", RoomLive.Show, :show
    live "/room/:id/show/edit", RoomLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", Manga2getherWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Manga2getherWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", Manga2getherWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", Manga2getherWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", Manga2getherWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/auth", Manga2getherWeb do
    pipe_through [:browser]

    get "/:provider", UserOAuthController, :request
    get "/:provider/callback", UserOAuthController, :callback
  end
end

lib/manga2gether_web/controllers/user_registration_controller.ex
defmodule Manga2getherWeb.UserRegistrationController do
  use Manga2getherWeb, :controller

  alias Manga2gether.Accounts
  alias Manga2gether.Accounts.User
  alias Manga2getherWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/manga2gether_web/views/user_registration_view.ex
defmodule Manga2getherWeb.UserRegistrationView do
  use Manga2getherWeb, :view
end

lib/manga2gether_web/templates/user_registration/new.html.eex
<div class="w-screen h-screen flex flex-col items-center bg-ebonyclay p-5">
	<div class="pt-10">
	  <h1 class="text-3xl text-center font-bold text-gallery">manga2gether</h1>
	</div>
	<div class="p-5">
	  <h2 class="text-2xl text-center font-bold text-gallery">Register</h2>
		<p class="pt-2 text-gallery text-center text-sm hover:text-bondiblue"><%= link "Or log in", to: Routes.user_session_path(@conn, :new) %></p>
	</div>

	<div class="w-10/12 max-w-lg bg-brightgray rounded-lg shadow-lg">
	  <%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
	    <%= if @changeset.action do %>
	      <div class="relative px-4 flex justify-center">
	        <p class="absolute text-red-500 font-light mt-4">Oops, something went wrong! Please check the errors below.</p>
	      </div>
	    <% end %>

			<div class="py-16 px-20 w-full">
				<div>
	  	    <%= label f, :username, class: "block text-sm py-1 text-gallery" %>
	  	    <%= text_input f, :username, required: true, class: "w-full rounded p-2 shadow-lg" %>
	  	    <%= error_tag f, :username %>
				</div>

				<div>
	  	  	<%= label f, :email, class: "block text-sm py-1 text-gallery" %>
	  	  	<%= email_input f, :email, required: true, class: "w-full rounded p-2 shadow-lg" %>
	  	  	<%= error_tag f, :email %>
				</div>

			<div>
	  	  	  <%= label f, :password, class: "block text-sm py-1 text-gallery" %>
	  	  	  <%= password_input f, :password, required: true, class: "w-full rounded p-2 shadow-lg" %>
	  	  	  <%= error_tag f, :password %>
			</div>

	  	    <div class="mt-6 w-full flex justify-center">
	  	      <%= submit "Register", class: "bg-bondiblue hover:bg-bondiblue-300 text-center text-ebonyclay py-3 rounded w-3/4 rounded-lg shadow-lg" %>
	  	    </div>

			<div class="flex flex-col items-center">
			  <!--
	  		  <p class="text-gallery hover:text-bondiblue font-light my-1">
	  		    <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
	  		  </p>
			  -->
			  <p class="text-gallery font-light my-1">Or</p>
			  <div class="text-center bg-bondiblue hover:bg-bondiblue-300 cursor-pointer w-3/4 rounded-lg shadow-lg text-ebonyclay py-3">
	  		    <%= link "Login with Discord", to: Routes.user_o_auth_path(@conn, :request, "discord") %>
			  </div>
			</div>

			</div>
	  <% end %>


	</div>
</div>